### ISSUE TITLE
Error "unknown context value" Raised After Checking for Existence

### ISSUE THREAD

**Issue by mi25iw** [gregsdennis/json-everything#713]
### Nuget Package

JsonE.Net

### Package Version

2.1.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

After an if (or switch) statement that checks if a variable/key exists, the `then` statement throws an `unknown context value` error even though the `if` check was false. For example, the [sample for `defined()`](https://json-e.js.org/built-ins.html#context) on the json-e page works in the online playground there but causes this error in JsonE.Net.

### What did you expect?

When an `if` or `switch` statement evaluates false, errors should not be thrown for non-existent values in the untaken branch.

### Please add test code or steps to reproduce the behavior.

Here are a few tests in the `more-tests.yml` format that fail, and my understanding from reading the spec and using the online [playground](https://json-e.js.org/playground.html) is that they should pass:

```yaml
---
title:    if defined check
context:  {y: 10}
template: {$if: 'defined("x")', then: {$eval: 'x'}, else: 20}
result:   20
---
title:    switch defined check
context:  {y: 10}
template: {$switch: {'defined("x")': {$eval: 'x'}, $default: 20}}
result:   20
```

The `template` can be copied to the playground to verify that at least in *their* implementation, this is supported.

### Is there any other information you'd like to share regarding this bug?

If this issue is accepted, it'd be great for these tests to be incorporated in the official json-e test suite in case it exists in other implementations.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.
